// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:clean_arch/Features/home/domain/entities/book_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters(BookEntityAdapter bookEntityAdapter) {
    registerAdapter(BookEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BookEntityAdapter());
  }
}
